/** Public API contract. Assign at the decision site; never derive from message text. */
export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
  CSRF_REJECTED = 'CSRF_REJECTED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  CONFLICT = 'CONFLICT',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_INVALID = 'SESSION_INVALID',
  STUDENT_ACCESS_INVALID = 'STUDENT_ACCESS_INVALID',
  ATTENDANCE_TOO_EARLY = 'ATTENDANCE_TOO_EARLY',
  ATTENDANCE_WINDOW_CLOSED = 'ATTENDANCE_WINDOW_CLOSED',
  ATTENDANCE_ALREADY_RECORDED = 'ATTENDANCE_ALREADY_RECORDED',
  ATTENDANCE_QR_INVALID = 'ATTENDANCE_QR_INVALID',
  ALLOWANCE_EXHAUSTED = 'ALLOWANCE_EXHAUSTED',
  ATTENDANCE_INELIGIBLE = 'ATTENDANCE_INELIGIBLE',
  ATTENDANCE_CORRECTION_BLOCKED = 'ATTENDANCE_CORRECTION_BLOCKED',
  CLASS_SESSION_FULL = 'CLASS_SESSION_FULL',
  CAPACITY_CONFLICT = 'CAPACITY_CONFLICT',
  RECOVERY_INVALID = 'RECOVERY_INVALID',
  RECOVERY_UNAVAILABLE = 'RECOVERY_UNAVAILABLE',
  RECOVERY_ALREADY_AUTHORIZED = 'RECOVERY_ALREADY_AUTHORIZED',
  REGULAR_ENROLLMENT_COVERS_TARGET = 'REGULAR_ENROLLMENT_COVERS_TARGET',
  STUDENT_INACTIVE = 'STUDENT_INACTIVE',
  PLAN_INACTIVE = 'PLAN_INACTIVE',
  SUBSCRIPTION_OVERLAP = 'SUBSCRIPTION_OVERLAP',
  PAYMENT_IDEMPOTENCY_CONFLICT = 'PAYMENT_IDEMPOTENCY_CONFLICT',
  PAYMENT_OVERPAYMENT = 'PAYMENT_OVERPAYMENT',
}

export function apiFailure(code: ErrorCode, message: string) {
  return { code, message };
}

export function defaultErrorCode(status: number): ErrorCode {
  return (
    (
      {
        400: ErrorCode.VALIDATION_FAILED,
        401: ErrorCode.UNAUTHORIZED,
        403: ErrorCode.FORBIDDEN,
        404: ErrorCode.NOT_FOUND,
        409: ErrorCode.CONFLICT,
        413: ErrorCode.PAYLOAD_TOO_LARGE,
        415: ErrorCode.UNSUPPORTED_MEDIA_TYPE,
        429: ErrorCode.RATE_LIMITED,
      } as Record<number, ErrorCode>
    )[status] ?? ErrorCode.INTERNAL_ERROR
  );
}

export function publicErrorCode(value: unknown): ErrorCode | undefined {
  return typeof value === 'string' &&
    Object.values(ErrorCode).includes(value as ErrorCode)
    ? (value as ErrorCode)
    : undefined;
}
