import { createRequire } from "node:module";
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import openapiTS, { astToString } from "openapi-typescript";

const backend = fileURLToPath(new URL("../../backend/", import.meta.url));
const require = createRequire(backend + "/package.json");
// Compile current sources to a temporary ignored directory, without changing backend files.
const output = fileURLToPath(new URL("../.openapi-build/", import.meta.url));
execFileSync(
  process.execPath,
  [
    require.resolve("typescript/bin/tsc"),
    "-p",
    backend + "/tsconfig.build.json",
    "--outDir",
    output,
    "--incremental",
    "false",
  ],
  { stdio: "inherit" },
);
Object.assign(process.env, {
  NODE_ENV: "test",
  DATABASE_URL: "postgresql://unused:unused@127.0.0.1:1/openapi_test",
  FRONTEND_ORIGIN: "http://localhost:5173",
  FRONTEND_ORIGINS: "http://localhost:5173",
  API_ORIGIN: "http://localhost:3000",
  COOKIE_SECURE: "false",
  SWAGGER_ENABLED: "true",
  TRUST_PROXY: "false",
});
const { NestFactory } = require("@nestjs/core");
const { DocumentBuilder, SwaggerModule } = require("@nestjs/swagger");
// Nest compiles CommonJS; a local package boundary prevents frontend ESM interpreting it.
await writeFile(output + "/package.json", '{"type":"commonjs"}');
const { AppModule } = require(output + "/app.module.js");
const { ApiErrorDto } = require(output + "/common/http/error-response.dto.js");
const app = await NestFactory.create(AppModule, {
  logger: false,
  abortOnError: false,
});
try {
  // NEVER call init/listen/configureApp: these connect Prisma and start reconciliation.
  app.setGlobalPrefix("api/v1");
  const config = new DocumentBuilder()
    .setTitle("Studio Gestión API")
    .setDescription("API para gestión de clases")
    .setVersion("0.1.0")
    .addCookieAuth("session", { type: "apiKey", in: "cookie" }, "session")
    .addGlobalResponse(
      ...[400, 401, 403, 404, 409, 413, 415, 429, 500].map((status) => ({
        status,
        type: ApiErrorDto,
      })),
    )
    .addTag("auth")
    .addTag("health")
    .addTag("admin")
    .addTag("student")
    .build();
  const document = SwaggerModule.createDocument(app, config);
  // Nest emits @Headers and @ApiHeader spellings. HTTP headers are case-insensitive.
  for (const path of Object.values(document.paths))
    for (const operation of Object.values(path)) {
      if (!operation || !Array.isArray(operation.parameters)) continue;
      const seen = new Set();
      operation.parameters = operation.parameters.filter((parameter) => {
        if (
          parameter.in !== "header" ||
          parameter.name.toLowerCase() !== "idempotency-key"
        )
          return true;
        parameter.name = "Idempotency-Key";
        if (seen.has(parameter.name)) return false;
        seen.add(parameter.name);
        return true;
      });
    }
  const json = JSON.stringify(document, null, 2) + "\n";
  const types =
    "// Generated by npm run api:generate; do not edit.\n" +
    astToString(await openapiTS(document));
  const folder = new URL("../src/shared/api/", import.meta.url);
  await mkdir(folder, { recursive: true });
  for (const [name, content] of [
    ["openapi.json", json],
    ["schema.d.ts", types],
  ]) {
    const path = new URL(name, folder);
    if (process.argv.includes("--check")) {
      if ((await readFile(path, "utf8")) !== content)
        throw new Error(name + " desactualizado: ejecutar api:generate");
    } else await writeFile(path, content);
  }
  console.log(
    "OpenAPI y tipos sincronizados; sin conexión DB ni servidor HTTP.",
  );
} finally {
  await app.close();
}
